openapi: 3.0.3
info:
  title: Price Catalog API
  description: API for retrieving price catalogs based on country Name codes.
  version: 1.0.0

paths:
  /API/priceCatalog/{index}:
    get:
      summary: Get price catalog for a specific country
      description: Retrieves a list of price data for the specified country based on the Name code.
      parameters:
        - name: index
          in: path
          required: true
          description: Name country code
          schema:
            type: string
            enum: ["SI"] # Add more country codes as needed
            example: "SI" # Default example value for the dropdown
      responses:
        '200':
          description: Successful response containing price data
          content:
            application/json:
              schema:
                type: object
                properties:
                  Name:
                    type: string
                    description: Name country code
                  Price:
                    type: array
                    description: List of timestamped price entries
                    items:
                      type: object
                      properties:
                        F:
                          type: string
                          format: date-time
                          description: From - ISO8601 formatted timestamp
                        T:
                          type: string
                          format: date-time
                          description: To - ISO8601 formatted timestamp
                        P:
                          type: number
                          format: float
                          description: Price value (MWh) at the given time range
                required:
                  - Name
                  - prices
        '400':
          description: Bad Request - Invalid ISO2 code format
        '404':
          description: Not Found - No price data for the specified country code
        '500':
          description: Internal Server Error

components:
  schemas:
    PriceEntry:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        price:
          type: number
